### ISSUE TITLE
V0.1.0 available?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [simonster/GLMNet.jl#16]
Hello. I just saw that GLMNet v0.1.0 has been released according to the GLMNet.jl site.
However, when I ran ```Pkg.update()```, my current GLMNet v0.0.5 was not updated to v0.1.0. I also tried to remove GLMNet v0.0.5 and reinstall GLMNet via ```Pkg.add("GLMNet")```, but still v0.0.5 was installed. Why does this happen and how can I get the v0.1.0 without using ```Pkg.checkout("GLMNet")```? Since v0.1.0 is an official release, I should be able to get that version simply by ```Pkg.update()``` in principle, correct?
Best,
BVPs

**Comment by simonbyrne** [comment]
The update to METADATA hasn't been merged yet.

**Comment by BoundaryValueProblems** [comment]
Thanks! Then, I need to wait a day or so, I guess.
By the way, it would be truly nice if you could address the gfortran compilation problem on Windows machines reported as follows: https://github.com/simonster/GLMNet.jl/issues/13
Looking at build.jl of v0.1.0, this has not been addressed yet. For v0.5.0, I had to revise build.jl manually for Windows machines.
Best,
BVPs

**Comment by BoundaryValueProblems** [comment]
Pkg.update() still does not update v0.0.5 to v0.1.0. 
26 days have passed since v0.1.0 is released. 
Has the update to METADATA been merged yet?
Thanks,
BVPs

**Comment by simonster** [comment]
It is available now.
