### ISSUE TITLE
Error attempting Logistic Regression

### ISSUE THREAD

**Issue by dhimmel** [simonster/GLMNet.jl#5]
I am encountering an error when trying to run a binomial logistic ridge regression. The error does not occur when using the default least squares regression.

```julia
import GLMNet
cv_guass = GLMNet.glmnetcv(X, y, GLMNet.Normal(), alpha=0.0)
cv_binom = GLMNet.glmnetcv(X, y, GLMNet.Binomial(), alpha=0.0)
```

The final line of code produces the following error:
```
no method glmnet!(Array{Any,1},Array{Float64,2},Array{Float64,1},Binomial)
at In[100]:3
 in glmnet at /home/dhimmels/.julia/v0.2/GLMNet/src/GLMNet.jl:346
 in glmnetcv at /home/dhimmels/.julia/v0.2/GLMNet/src/GLMNet.jl:382
```

I am new to julia, so perhaps I'm missing something. Thanks.

**Comment by IainNZ** [comment]
@simonster I'd be interested about the `lambda.1se` thing too, if you know.

**Comment by simonster** [comment]
I would guess `lambda.1se` is something like:

```julia
minloss, index = findmin(cv.meanloss)
max(lambda[cv.meanloss .<= minloss+cv.stdloss[index]])
```

but I'll double-check with the R interface tomorrow.

**Comment by simonster** [comment]
[This](https://github.com/jeffwong/glmnet/blob/af4484dfb869623afce8eef03aa6ec7eab98cf96/R/getmin.R) is the R code that computes `lambda.1se`. What I wrote above seems right. I'll include this when I get around to making a general cross validation framework for my various Lasso packages.

**Comment by dhimmel** [comment]
Great, thanks for the interim solution to calculate `lambda` using the 'one-standard error rule'.
