### ISSUE TITLE
Problem with Pkg.add("GLMNet") in Julia 0.3.3 on Mac, OS 10.9.5

### ISSUE THREAD

**Issue by pszolovits** [simonster/GLMNet.jl#8]
It appears that the build of this package, using gfortran on OS X 10.9.5, tries to use the -shared option which is not present.

julia> Pkg.build("GLMNet")
INFO: Building GLMNet
i686-apple-darwin8-gfortran-4.2: unrecognized option '-shared'
Undefined symbols for architecture x86_64:
  "_MAIN__", referenced from:
      _main in libgfortranbegin.a(fmain.o)
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
========================================[ ERROR: GLMNet ]========================================

failed process: Process(`gfortran -m64 -fdefault-real-8 -ffixed-form -fPIC -shared -O3 glmnet3.f90 -o libglmnet.so`, ProcessExited(1)) [1]
while loading /Users/psz/.julia/v0.3/GLMNet/deps/build.jl, in expression starting on line 3

**Comment by simonster** [comment]
Where did your gfortran build come from? This builds fine for me on 10.10.2 with gfortran from Homebrew.

**Comment by pszolovits** [comment]
I don't recall, but there was apparently something problematic with my Homebrew installation.  I reinstalled it and then gfortran seems to work.  Thanks.
